# Generated by Django 5.2.8 on 2025-11-23 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('ANNUAL', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('KIOSCO', 'Kiosco'), ('PYME', 'PyME'), ('CLOTHING', 'Indumentaria'), ('FOOD', 'Gastronomía'), ('SERVICES', 'Servicios')], default='PYME', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_image', models.ImageField(upload_to='sub_proofs/')),
                ('plan_selected', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('ANNUAL', 'Anual')], max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
